# Activar el perfil de secretos
spring.profiles.active=secret

# Configuración de Base de Datos (us-west-2)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci?n de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuraci?n de Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nestorutog@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
