# Nueva configuración usando el Connection Pooler (Soporta IPv4)
# Esto carga las variables de tu archivo secreto local
spring.profiles.include=secret

# Tus configuraciones normales (públicas)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dophoswgcczqhwieueyy

# Clave falsa para GitHub
spring.datasource.password=PONER_CLAVE_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Eliminamos la línea del dialecto manual para que Hibernate 7 lo detecte solo
# Cambia 'update' o 'create' por 'none'


# ==========================================
# CONFIGURACIÓN DE CORREO (GMAIL SMTP)
# ==========================================
# Importamos las credenciales desde el archivo secreto ignorado por Git
spring.config.import=optional:classpath:application-secrets.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
