# Nueva configuración usando el Connection Pooler (Soporta IPv4)
# Esto carga las variables de tu archivo secreto local
spring.profiles.include=secret

# Tus configuraciones normales (públicas)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dophoswgcczqhwieueyy

# Clave falsa para GitHub
spring.datasource.password=PONER_CLAVE_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Eliminamos la línea del dialecto manual para que Hibernate 7 lo detecte solo
# Cambia 'update' o 'create' por 'none'
